# Generated by Django 5.0.6 on 2024-06-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
